# Generated by Django 3.2.6 on 2021-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210830_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='institute',
        ),
        migrations.AddField(
            model_name='membereducation',
            name='institute',
            field=models.CharField(choices=[('Punjab Clg', 'Punjab Clg'), ('Fast Nuces', 'Fast Nuces')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
