# Generated by Django 3.2.6 on 2021-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210830_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='myapp.Skill'),
        ),
    ]
